### ISSUE TITLE
How many images reconstructed given batch size > 1?

### ISSUE THREAD

**Issue by ruotongyu** [JonasGeiping/invertinggradients#11]
Thanks for releasing the code. I have a question about the number of images reconstructed given batch size greater than 1. From my understanding, the images reconstructed should be the same number as the batch size. Please correct me if my understanding is wrong. Really appreciate your help.

**Comment by JonasGeiping** [comment]
Hi, could you clarify your question? I think this depends on the goal of the attack. Does the attack try to recover all images contained in a batch or only some, or any?

**Comment by ruotongyu** [comment]
Thanks for quick rely. I am curious about how gradient inversion attack achieve this in general. Are they trying to recover all images contained in a batch (given the labels)? If so, what happens if the batch containing more than one data from the same class? I am assuming the recovered images from the same class should be highly similar to each other. The examples only demonstrate the case where batch size is one. Again, really appreciate your help.

**Comment by JonasGeiping** [comment]
Yes, the default approach would be to recover all unknown images in the batch. You can experiment with this in the code, for example see here: https://github.com/JonasGeiping/invertinggradients/blob/master/Multiple%20images%20and%20multiple%20local%20update%20steps%20(ConvNet).ipynb
(where the deer and frog labels repeat).

In theory you can still expect to recover multiple images even when they share the same label, as neural network activation patterns can be different for both images. In general though, the more images are in the batch, the harder this becomes. More modern attacks have improved on this through stronger priors of what natural images look like.

**Comment by JonasGeiping** [comment]
I hope this answers your question. Feel free to reopen this thread otherwise!
