### ISSUE TITLE
how to extract intermediate images before the reconstructed output in ipynb notebooks.

### ISSUE THREAD

**Issue by ShristiDasBiswas** [JonasGeiping/invertinggradients#15]
Hi, how can i extract the intermediate images before the final reconstructed output?

**Comment by JonasGeiping** [comment]
I would add a callback or export in the vicinity of this:

https://github.com/JonasGeiping/invertinggradients/blob/1157b61c6704df42c497ab9eb074c75da5204334/inversefed/reconstruction_algorithms.py#L174

**Comment by ShristiDasBiswas** [comment]
Hi, thanks for your reply! should i export the `x_trial.data` variable in this file at every iteration? is that the intermediate image at each iteration?

**Comment by JonasGeiping** [comment]
Yeah
