### ISSUE TITLE
factor used in calculating PSNR

### ISSUE THREAD

**Issue by zliangak** [JonasGeiping/invertinggradients#3]
Hi Jonas, here is another question. In your jupyter notebook, for example "Recovery from Gradient Information.ipynb", you use
```
test_psnr = inversefed.metrics.psnr(output, ground_truth)
```
to calculate the PSNR of the recovered image (parameter factor=1). However, in "reconstruct_image.py", you used: https://github.com/JonasGeiping/invertinggradients/blob/414bfb93af379f29f19d5b94d3128990b4ee9dc7/reconstruct_image.py#L207

The later one use an extract factor 1/ds. I am wondering which one should be used. According to my understanding, the later one would be correct. Am I right?

**Comment by JonasGeiping** [comment]
Hi, you correct this is an oversight in the jupyter notebook. The data is normalized and as such the PSNR formula has to be modified to account for the new maximal value as in the command-line script. 

I'll push a fix to this problem. Thank you for letting us know :+1:

**Comment by Stephenhua** [comment]
Hi Jonas, I am not clear that it need to an extract factor I/ds when the data is normalized. noramlze formula as follows :
`x_i= (X_i-Mean)/std`
but PSNR formula as this :
`PSNR = 10 *log_10 (MAX)^2/MSE`,
So, it means that 1/ds =MAX , Is there a new formula for this conversion process?
Looking forward to your reply. Thanks

**Comment by JonasGeiping** [comment]
Hi, the standard interval [0,1] has a maximal value of 1, but when images from this range are normalized, the new interval is [-mean/std, (1+mean)/std]. The offset by the mean is a constant that does not change PSNR, but the change is scale has to be taken into account, so that the PSNR is the same, whether the image is normalized, or not.

**Comment by Stephenhua** [comment]
Thank you, I have known  what's your means. But,  I think  the new interval  what you say , it should be " (1-mean)/std)" , not " (1+mean)/std)".  Am I right?

**Comment by JonasGeiping** [comment]
yes
