### ISSUE TITLE
About loss_step function

### ISSUE THREAD

**Issue by zliangak** [JonasGeiping/invertinggradients#4]
Hi, when I try to reproduce the result in Table where `epoch=5`, `num_images=1` and `batch_size=1`, I got an error saying that batchsizes mismatch. I look into the code and find that in the loss_step function, the `inputs` is iterated by index `idx` while `labels_` is iterated by index `i`. If we enumerate the labels more than once, then it will go out of the list.

https://github.com/JonasGeiping/invertinggradients/blob/8fcd8c213c563389fc4d981a22cedc952da08827/inversefed/reconstruction_algorithms.py#L309

I think the correct one should be  
`labels_ = labels[idx * batch_size:(idx + 1) * batch_size]`, which complies with the `inputs`.

**Comment by bauermeisterh** [comment]
Hi @zliangak,
you are completely right, we've just fixed this issue! For taking the full batch at each iteration, you can alternatively also use the option `batch_size=0`. That's also why have not been aware of the issue so far.
