### ISSUE TITLE
How do you handle the pairing when batch size > 1

### ISSUE THREAD

**Issue by zjysteven** [JonasGeiping/invertinggradients#7]
Hi Jonas,

First big thanks to you for making this repo public, which facilitate my work a lot. I have a question regarding the evaluation of a batch of images. So suppose the target batch has images of ['bird', 'car', 'plane'], and after reconstruction the recovered batch may or may not have the same order as the target batch, e.g., being ['car', 'plane', 'bird']. Then to measure the pair-wise metrics like MSE/PSNR, I suppose that we need to first reorder the recovered batch such that it matches the target batch. However, I didn't see how you handle this in either `reconstruction_algorithms.py` or those notebooks. I could be missing or misunderstanding something, so some discussion or clarification would be really appreciated!

Thanks,
Steven

**Comment by JonasGeiping** [comment]
Hello Steven,

under the assumption that labels are known (from some other scheme, such as from the various papers on label recovery), this problem doesn't come up for a batch of unique labels. The reconstruction recovers images in the same batch order as they are presented in the label vector. This is exactly equally difficult as recovering from an arbitrary permutation of the label vector.

As soon as the batch contains non-unique labels, e.g. multiple birds, however, this becomes more interesting, as now multiple orderings of images are possible. Ideally now you would want to match images first to their target images, before computing their PSNR. We don't implement this, so our PSNR values are only an underapproximation of the optimal "matched" PSNR for this case of non-unique labels in the label vector.

Best Regards,
Jonas

**Comment by zjysteven** [comment]
Ok I see. Thanks for your prompt response!
