### ISSUE TITLE
Reproducibility issue 

### ISSUE THREAD

**Issue by soheejun** [JonasGeiping/invertinggradients#8]
Thanks for your work. 
I have an issue on the reproducibility

 I set the seed using'set_random_seed' function. 
and construct the model with the seed. 
However, with running several times on the same code, the results after Iter 0 is changed. 
I can not find the randomness in the optimization progress. 
How can I reproduce the result on the same data and model. 

Thanks

**Comment by JonasGeiping** [comment]
Hi, what do you want to reproduce? The numbers that we report, or do you want to have reproducible experiments in general? For the first, running  `rec_mult.py` with the desired settings and dataset subset should lead to results within tolerance. 
For the second (perfectly reproducible experiments in general), the code should also be switched into deterministic mode via args.deterministic, although the function to do that should proabably be updated for newer pytorch version to 
```
def set_deterministic():
    """Switch pytorch into a deterministic computation mode."""
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.use_deterministic_algorithms(True)
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
```

**Comment by soheejun** [comment]
Thanks for quick reply, 
I want to reproduce the result on my own data and the model. 
Based on your advice, I will apply deterministic setting for reproducibility. 

By the way, where is the randomness in the optimization progress? 
I think if the input gradients, weights, and init x will show the same result, but it does not.

**Comment by JonasGeiping** [comment]
The main source of explicit randomness is indeed the initialization of x. For a fixed model and fixed data point there is no other randomness introduced. Interesting, maybe set_random_seed is not capturing all random events?

**Comment by soheejun** [comment]
Yes, I set set_random_seed (not deterministic setting), and use same initialization of  x as 'zeros' mode. 
But the results are different, when I run the same code with same data several times. 

With the determisitic setting, the results are the same. 
I just wonder why the randomness is not controlled by the set_random_seed.

**Comment by JonasGeiping** [comment]
Ok, if the results are the same in the deterministic setting, then this makes sense. 

There is no additional randomness here that could be seeded and controlled with set_random_seed. The remaining randomness arises from non-deterministic algorithm implementations. Even small sources of  randomness (like order of floating point additions) can lead to different behavior.

**Comment by soheejun** [comment]
Now I understand the issue. 
Thank you for your prompt reply, and 
thanks for the all your kind replies!
