### ISSUE TITLE
some question about label_flip

### ISSUE THREAD

**Issue by lhq12** [JonasGeiping/invertinggradients#9]
Hello @JonasGeiping:

Thank you for your great work.
I am confused about the purpose of the "label_flip" argument. I will appreciate it if you could explain a bit more. And also when I try to run this code by "python reconstruct_image.py --model ResNet20-4 --dataset CIFAR10 --trained_model --cost_fn sim --indices def --restarts 1 --save_image --target_id 1 --label_flip", it returns an error of this line. https://github.com/JonasGeiping/invertinggradients/blob/2d5bb7529ef4f2c005ba5a925f8688015c62b115/reconstruct_image.py#L79
I'm looking forward to your kindly reply.

Thanks.

**Comment by JonasGeiping** [comment]
Hi,

this option flips the label to a wrong label. This is an implementation trick to implement what is actually a malicious parameter modification: Two rows in the final linear layer (with weights their corresponding biases) are switched. 

The idea is described in more detail in our appendix as a possible malicious parameter modification. Note that this falls outside the usual honest-but-curious model.


I've pushed a small fix to restore this option to working condition.

**Comment by lhq12** [comment]
Thank you very much for the explanation！I can understand it now.
